[book]
authors = ["James Munns"]
language = "es"
src = "src"
title = "El libro de Rust Embebido"

[output.html]
site-url = "https://embedded-book.rustlang-es.org"
git-repository-url = "https://github.com/RustLangES/rust-embedded-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/RustLangES/rust-embedded-book/edit/main/{path}"
